### ISSUE TITLE
Keywords Trigger Snippet Insertion Prematurely

### ISSUE THREAD

**Issue by yucchi-p** [raycast/ray-so#104]
Description:

When using the snippet feature in Raycast, the snippet gets inserted as soon as the keywords are typed. This behavior interrupts the normal flow of typing and can be frustrating for users who need to complete their input before the snippet should be inserted.

Steps to Reproduce:

	1.	Open Raycast and go to the snippet feature.
	2.	Type in the keywords for a specific snippet.
	3.	Observe that the snippet gets inserted immediately after typing the keywords.

Expected Behavior:

The snippet should only be inserted when the user confirms the insertion, such as pressing a specific key or completing the keyword input with a defined action.

Actual Behavior:

The snippet is inserted prematurely as soon as the keywords are typed, without any additional confirmation from the user.

Environment:

	•	Raycast version: 1.80.0
	•	OS: 14.5（23F79）

**Comment by yucchi-p** [comment]
![Area](https://github.com/user-attachments/assets/b14ee57f-563b-429e-808d-d9b19c2ea784)

**Comment by samuelkraft** [comment]
Hey @yucchi-p! This repository is for issues related to the ray.so ecosystem. Support questions are better asked in the community Slack or by emailing hello@raycast.com.

To answer your question, you can assign a modifier, such as `!td`.

![Sam 2024-08-07 at 2:50 31@2x](https://github.com/user-attachments/assets/6721ac90-2931-433d-a1fd-850176b27641)
