### ISSUE TITLE
Avoid clipboard history to store passwords

### ISSUE THREAD

**Issue by dimitriacosta** [raycast/ray-so#124]
I've been using the clipboard history very frequently and I noticed that whenever I copy a password from 1Password on my personal computer the password is ignored but when I copy a password that is stored on Safari's password manager or KeePassX, which I use at my work's computer for compliance, the password is stored in the clipboard history and this should not happen, is there a way to ignore those?
![Screenshot 2024-09-04 at 16 28 29](https://github.com/user-attachments/assets/9d868758-82c5-430e-9f10-706de3f7f7b3)
![Screenshot 2024-09-04 at 16 33 46](https://github.com/user-attachments/assets/8c0b4dd3-6607-49d7-a844-4a4075a0b60f)
![Screenshot 2024-09-04 at 16 28 52](https://github.com/user-attachments/assets/34971bc1-9003-4730-baa7-71ca8c980021)

**Comment by samuelkraft** [comment]
Hey @dimitriacosta ! This repository is for issues related to the ray.so ecosystem. Support questions are better asked in the community Slack or by emailing [hello@raycast.com](mailto:hello@raycast.com).

To give a quick answer to your question, you can disable applications from being included in the clipboard history settings.

![Sam 2024-09-05 at 10  34 36@2x](https://github.com/user-attachments/assets/ee45d358-393a-4f03-9209-a5fdf8a9754f)

**Comment by dimitriacosta** [comment]
Thank you @samuelkraft I didn't know where to post this so sorry if this wasn't supposed to be here.
Anyways thanks for the information, I'll add those to the disabled applications list.
