### ISSUE TITLE
 Add the ability to self-host via pre-built container image for docker-compose stack

### ISSUE THREAD

**Issue by jo-chemla** [raycast/ray-so#79]
Congrats on open-sourcing the raycast ecosystem!

Publishing pre-built container images on docker-hub or ghcr would be useful for self-hosters to host ray.so - especially the `Code Images` generator - on their own terms and server. Accompanying the container image with an example docker-compose yaml stack would also be useful to facilitate self-hosting.

**Comment by samuelkraft** [comment]
Hi @jo-chemla, thanks for the suggestion! We're currently focusing on improving the ecosystem itself, so we won't be prioritizing docker images at this time.

**Comment by jo-chemla** [comment]
Thanks for getting back and understand the reply. 
Would you be wiling to let this issue open in case anyone wants to tackle that challenge and eventually do a PR? 
Facilitating self-hosting setup might as well result in some traction for rayso itself. 

There are multiple guides (eg [1](https://rainerregan.medium.com/how-to-dockerize-next-js-app-b73e0134f973), [2](https://medium.com/@itsuki.enjoy/dockerize-a-next-js-app-4b03021e084d)), maybe someone will want to give it a hand at some point.
