### ISSUE TITLE
feature request: display line number & lines higlight

### ISSUE THREAD

**Issue by himself65** [raycast/ray-so#81]

**Comment by abishekrsrikaanth** [comment]
Would love to have this feature

**Comment by samuelkraft** [comment]
You can highlight lines by ⌥ + click on a line.
Displaying line numbers is supported but does not have a UI yet, it can be enabled by adding `lineNumbers=true` in the url params e.g. https://ray.so/#lineNumbers=true&theme=candy&highlightedLines=6%2C7%2C3%2C4%2C5&code=aW1wb3J0IHsgRGV0YWlsIH0gZnJvbSAiQHJheWNhc3QvYXBpIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIENvbW1hbmQoKSB7CiAgcmV0dXJuIDxEZXRhaWwgbWFya2Rvd249IkhlbGxvIFdvcmxkIiAvPjsKfQ
